env: "local"
http_server:
  address: "localhost:8084"
  timeout: 5s
  idle_timeout: 60s
database:
  host: localhost
  port: 5432
  username: postgres
  password: 1234567
  dbname: auth
jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 30m
  secret_key: "kqaU4SzYnwvr2qkriHO7aUUnh1KRsfxmcsobqUaHr1U="